#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\matrix.exe

OBJ_RELEASE = $(OBJDIR_RELEASE)\\AutoDiff_lib.o $(OBJDIR_RELEASE)\\Matrix_lib.o $(OBJDIR_RELEASE)\\Numerical_lib.o $(OBJDIR_RELEASE)\\Vector_lib.o $(OBJDIR_RELEASE)\\fft.o $(OBJDIR_RELEASE)\\lib_basic.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\pch.o

all: release

clean: clean_release

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\AutoDiff_lib.o: AutoDiff_lib.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c AutoDiff_lib.cpp -o $(OBJDIR_RELEASE)\\AutoDiff_lib.o

$(OBJDIR_RELEASE)\\Matrix_lib.o: Matrix_lib.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Matrix_lib.cpp -o $(OBJDIR_RELEASE)\\Matrix_lib.o

$(OBJDIR_RELEASE)\\Numerical_lib.o: Numerical_lib.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Numerical_lib.cpp -o $(OBJDIR_RELEASE)\\Numerical_lib.o

$(OBJDIR_RELEASE)\\Vector_lib.o: Vector_lib.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Vector_lib.cpp -o $(OBJDIR_RELEASE)\\Vector_lib.o

$(OBJDIR_RELEASE)\\fft.o: fft.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c fft.cpp -o $(OBJDIR_RELEASE)\\fft.o

$(OBJDIR_RELEASE)\\lib_basic.o: lib_basic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib_basic.cpp -o $(OBJDIR_RELEASE)\\lib_basic.o

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\pch.o: pch.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c pch.cpp -o $(OBJDIR_RELEASE)\\pch.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_release after_release clean_release

